# Generated by Django 4.2.6 on 2023-11-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
                ('availableSeats', models.IntegerField(default=0)),
            ],
        ),
    ]
