# Generated by Django 4.2.6 on 2023-11-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='arrivalTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carpool',
            name='departureTime',
            field=models.IntegerField(default=0),
        ),
    ]
