# Generated by Django 4.2.6 on 2023-11-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_carpool_arrivaltime_carpool_departuretime'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
